
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Note1
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jButton5 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        jButton5.setText("Pessoas");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("jToggleButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(120, 120));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 120));

        jButton2.setText("Salas");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(71, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(71, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(71, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Pessoas");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTROS");
        jLabel1.setToolTipText("");

        jToggleButton1.setText("Espaços");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setMinimumSize(new java.awt.Dimension(120, 120));
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 120));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONSULTAS");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton3.setText("Pessoas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Salas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("Espaço de café");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Processamentos");

        jButton6.setText("Fazer ensalamento");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFrame consP = new ConsultasPessoas();
        consP.setVisible(true);
        consP.setDefaultCloseOperation( JFrame.DISPOSE_ON_CLOSE);
        consP.setSize( 600, 600 );
        consP.setLocationRelativeTo(null);
//      Processo para abrir a janela das consultas de pessoas, definir o tamanho e para fechar apenas uma
//      janela ao apertar no X.  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame cadP = new CadastrosPessoas();
        cadP.setVisible(true);
        cadP.setDefaultCloseOperation( JFrame.DISPOSE_ON_CLOSE);
        cadP.setSize( 600, 600 );
        cadP.setLocationRelativeTo(null);
//      Processo para abrir a janela dos cadastros de pessoas, definir o tamanho e para fechar apenas uma
//      janela ao apertar no X.
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFrame cadS = new CadastrosSalas();
        cadS.setVisible(true);
        cadS.setDefaultCloseOperation( JFrame.DISPOSE_ON_CLOSE);
        cadS.setSize( 600, 600);
        cadS.setLocationRelativeTo(null);
//      Processo para abrir a janela de cadastros de salas, definir o tamanho e para fechar apenas uma
//      janela ao apertar no X.        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFrame consS = new ConsultasSalas();
        consS.setVisible(true);
        consS.setDefaultCloseOperation( JFrame.DISPOSE_ON_CLOSE);
        consS.setSize( 600, 600);
        consS.setLocationRelativeTo(null);
//      Processo para abrir a janela das consultas das salas, definir o tamanho e para fechar apenas uma
//      janela ao apertar no X.        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        JFrame cadS = new CadastrosCafé();
        cadS.setVisible(true);
        cadS.setDefaultCloseOperation( JFrame.DISPOSE_ON_CLOSE);
        cadS.setSize( 600, 600);
        cadS.setLocationRelativeTo(null);
//      Processo para abrir a janela dos cadastros dos espaço de café, definir o tamanho e para fechar 
//      apenas uma janela ao apertar no X.        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/dados", "root", "");
        Statement stmt = con.createStatement();
        String sql = "update pessoas set etapa1 = 0, etapa2 = 0, intervalo1 = 0, intervalo2 = 0 where id <> 0";
        stmt.executeUpdate(sql);
        
        ResultSet rs = null;
        sql = "select * from cafe";       
        rs = stmt.executeQuery(sql);
        ArrayList<Integer> salaCafe = new ArrayList<Integer>();
        ArrayList<Integer> lotCafe = new ArrayList<Integer>();
        int numCafe = 0;
        if(rs != null){
            while(rs.next()){
                salaCafe.add(rs.getInt("id"));
                lotCafe.add(rs.getInt("lotacao"));
                numCafe = numCafe + 1;
            }
//          Nessa parte o programa calcula o numero de espaços de café que foram cadastrados.
        }
        
        ResultSet rs = null;
        sql = "select * from salas";       
        rs = stmt.executeQuery(sql);
        ArrayList<Integer> salas = new ArrayList<Integer>();
        ArrayList<Integer> lotacao = new ArrayList<Integer>();       
        int numSalas = 0;
        if(rs != null){
            while(rs.next()){
                salas.add(rs.getInt("id"));
                lotacao.add(rs.getInt("lotacao"));
                numSalas = numSalas + 1;                
            } 
//          Nessa parte o programa calcula o numero de salas que foram cadastrados.
        }    
        int detSala = 0;
        int detCafe = 0;
                
        ResultSet rs = null;
        sql = "select * from pessoas";
        rs = stmt.executeQuery(sql);
        if(rs != null){
            while(rs.next()){
//              System.out.println(rs.getString("nome") + " " + rs.getString("sobrenome"));
                sql = "update pessoas set etapa1 = " + salas.get(detSala) + ", etapa2 = " + salas.get(detSala) + " where id = " + rs.getString("id");
                Statement stmt = con.createStatement();
                stmt.executeUpdate(sql);
                detSala = detSala + 1;
                if(detSala == numSalas){
                    detSala = 0;
//              Nessa parte é feita a divisão para qual sala a pessoa irá no treinamento.  
                }            
            }            
        }
        ResultSet rs = null;
        sql = "select * from pessoas";
        rs = stmt.executeQuery(sql);
        if(rs != null){
            while(rs.next()){
                sql = "update pessoas set intervalo1 = " + salas.get(detCafe) + ", intervalo2 = "+salas.get(detCafe)+"  where id = " + rs.getString("id");
                Statement stmt = con.createStatement();
                stmt.executeUpdate(sql);
                detCafe = detCafe + 1;
                if(detCafe == 2){
                    detCafe = 0;
                }
//          Nessa parte, determina para qual espaço de café a pessoa irá nos intervalos. 
            }
        }
        
        ResultSet rs = null;
        int salaAnt = 0;
        for(int x = 0; x < salas.size(); x++){
            sql = "select count(*) as tot from pessoas where etapa1 = " + salas.get(x);
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            rs.next();
//            System.out.println(rs.getString("tot"));
            int metade = (int)rs.getInt("tot")/2;
            sql = "select * from pessoas where etapa1 = " + salas.get(x);
            stmt = con.createStatement();
            rs = stmt.executeQuery(sql);
            rs.next();
            for(int y = 1; y <= metade; y++){
                sql = "update pessoas set etapa2 = " + salaAnt + " where id = " + rs.getString("id");
                stmt = con.createStatement();
                stmt.executeUpdate(sql);
                rs.next();                
            }  
            salaAnt = salas.get(x);
//            System.out.println(salaAnt);
//      Esse processo determina quais pessoas irão mudar de sala (dividindo a turma por 2 - 50%).
        }
        sql = "update pessoas set etapa2 = " + salaAnt + " where etapa2 = 0";
        stmt = con.createStatement();
        stmt.executeUpdate(sql);
        
        sql = "select * from salas";
        stmt = con.createStatement();
        rs = stmt.executeQuery(sql);
        String sql1 = "";
        Statement stmt1 = con.createStatement();
        ResultSet rs1 = null;
        int totEtapa1;
        int totEtapa2;
        String maxLot = "";
        
        while(rs.next()){
            sql1 = "select count(*) as tot from pessoas where etapa1 = " + rs.getString("id");
            stmt1 = con.createStatement();
            rs1 = stmt1.executeQuery(sql1);
            rs1.next();
            totEtapa1 = rs1.getInt("tot");
            
            sql1 = "select count(*) as tot from pessoas where etapa2 = " + rs.getString("id");
            stmt1 = con.createStatement();
            rs1 = stmt1.executeQuery(sql1);
            rs1.next();
            totEtapa2 = rs1.getInt("tot");
            
            if((totEtapa1 > rs.getInt("lotacao")) || (totEtapa2 > rs.getInt("lotacao"))){
                maxLot = maxLot + "Sala " + rs.getString("sala") + " excede o limite de lotação!" + "\n";
            }
//      Esse processo verifica a lotação e dá um aviso caso o número de pessoas na sala exceda o limite
//      da lotação daquele local.
        }
        
        JOptionPane.showMessageDialog(null, maxLot + "Processo concluído!");
        rs.close();
        con.close();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JFrame consC = new ConsultasCafe();
        consC.setVisible(true);
        consC.setDefaultCloseOperation( JFrame.DISPOSE_ON_CLOSE);
        consC.setSize( 600, 600);
        consC.setLocationRelativeTo(null);
//      Processo para abrir a janela das consultas de espaço de café, definir o tamanho e para fechar 
//      apenas uma janela ao apertar no X.  
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
